### ISSUE TITLE
求打包一个.deb的linux可用版本

### ISSUE THREAD

**Issue by iorebuild** [ErLinErYi/PlantsVsZombies#1]
求打包一个.deb的linux可用版本，linux不能玩游戏，有时候代码写的很类，想玩玩植物大战僵尸，谢谢开发和开源

**Comment by ErLinErYi** [comment]
如果你很急的话可以自己打包linux版本，这个是用cocos2dx开发的，可以跨平台的。



---原始邮件---
发件人: "liyepan"<notifications@github.com&gt;
发送时间: 2020年2月2日(周日) 下午4:21
收件人: "ErLinErYi/PlantsVsZombies"<PlantsVsZombies@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [ErLinErYi/PlantsVsZombies] 求打包一个.deb的linux可用版本 (#1)



求打包一个.deb的linux可用版本，linux不能玩游戏，有时候代码写的很类，想玩玩植物大战僵尸，谢谢开发和开源

**Comment by kurt-steiner** [comment]
@ErLinErYi please tell us how to build it, I don't know about cocos2dx

**Comment by Xi-Gong** [comment]
Follow ErLinErYi pvz project, I develop a cocos2dx Linux version which build by CMake. Welcome to check the repo [https://github.com/Xi-Gong/Plants-Vs-Zombies](url)
