### ISSUE TITLE
考虑开Wiki和Discussion功能吗

### ISSUE THREAD

**Issue by KeyFac** [ErLinErYi/PlantsVsZombies#10]

**Comment by KeyFac** [comment]
说不定会有什么意外的收获呢

**Comment by KeyFac** [comment]
可以写一写翻译事宜与格式，具体的解释等
Discussions可以进行讨论，说不定就找到这么好东西了呢

**Comment by ErLinErYi** [comment]
OK, I'll try it tomorrow



---原始邮件---
发件人: "GLgele"<notifications@github.com&gt;
发送时间: 2021年1月28日(周四) 晚上9:46
收件人: "ErLinErYi/PlantsVsZombies"<PlantsVsZombies@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: Re: [ErLinErYi/PlantsVsZombies] 考虑开Wiki和Discussion功能吗 (#10)




 
可以写一写翻译事宜与格式，具体的解释等
 Discussions可以进行讨论，说不定就找到这么好东西了呢
