### ISSUE TITLE
窗口化如何修改分辨率呢？

### ISSUE THREAD

**Issue by gggfk008** [ErLinErYi/PlantsVsZombies#19]
窗口化如何修改分辨率呢？

**Comment by ErLinErYi** [comment]
在lzappdelegate.cpp文件中有设定窗口的大小



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年6月8日(周三) 下午4:02
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [ErLinErYi/PlantsVsZombies] 窗口化如何修改分辨率呢？ (Issue #19)




 
窗口化如何修改分辨率呢？
