### ISSUE TITLE
IOS版本

### ISSUE THREAD

**Issue by ghost** [ErLinErYi/PlantsVsZombies#20]
可以提供IOS的安裝檔嗎？沒有Android手機。

**Comment by ErLinErYi** [comment]
由于本人并没有ios版本的开发设备，所以不会提供ios版本。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ErLinErYi/PlantsVsZombies"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年8月9日(星期二) 下午5:06
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[ErLinErYi/PlantsVsZombies] IOS版本 (Issue #20)





 
可以提供IOS的安裝檔嗎？沒有Android手機。
