### ISSUE TITLE
完整代码下载

### ISSUE THREAD

**Issue by danielstock** [ErLinErYi/PlantsVsZombies#3]
您好，想学习手机游戏开发，能否提供完整代码包下载，谢谢啦

**Comment by ErLinErYi** [comment]
由于我正在重建仓库，请稍等一些时间就可以下载了。



---原始邮件---
发件人: "danielstock"<notifications@github.com&gt;
发送时间: 2020年2月29日(周六) 中午11:33
收件人: "ErLinErYi/PlantsVsZombies"<PlantsVsZombies@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [ErLinErYi/PlantsVsZombies] 完整代码下载 (#3)



您好，想学习手机游戏开发，能否提供完整代码包下载，谢谢啦

**Comment by danielstock** [comment]
好的，谢谢。
请问您用ecipse还是android studio开发的




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"LZ"<notifications@github.com&gt;;
发送时间:&nbsp;2020年2月29日(星期六) 中午12:04
收件人:&nbsp;"ErLinErYi/PlantsVsZombies"<PlantsVsZombies@noreply.github.com&gt;;
抄送:&nbsp;"danieldaniel"<danielstock@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [ErLinErYi/PlantsVsZombies] 完整代码下载 (#3)



由于我正在重建仓库，请稍等一些时间就可以下载了。 
 
 
 
 ---原始邮件--- 
 发件人: "danielstock"<notifications@github.com&amp;gt; 
 发送时间: 2020年2月29日(周六) 中午11:33 
 收件人: "ErLinErYi/PlantsVsZombies"<PlantsVsZombies@noreply.github.com&amp;gt;; 
 抄送: "Subscribed"<subscribed@noreply.github.com&amp;gt;; 
 主题: [ErLinErYi/PlantsVsZombies] 完整代码下载 (#3) 
 
 
 
 您好，想学习手机游戏开发，能否提供完整代码包下载，谢谢啦

**Comment by ErLinErYi** [comment]
我是用visual studio2019开发的。不过cocos2dx是跨平台的。可以导入到android studio或eclipse中。



---原始邮件---
发件人: "danielstock"<notifications@github.com&gt;
发送时间: 2020年3月1日(周日) 中午11:13
收件人: "ErLinErYi/PlantsVsZombies"<PlantsVsZombies@noreply.github.com&gt;;
抄送: "Comment"<comment@noreply.github.com&gt;;"LZ"<2117610943@qq.com&gt;;
主题: Re: [ErLinErYi/PlantsVsZombies] 完整代码下载 (#3)


好的，谢谢。 
 请问您用ecipse还是android studio开发的 
 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人:&amp;nbsp;"LZ"<notifications@github.com&amp;gt;; 
 发送时间:&amp;nbsp;2020年2月29日(星期六) 中午12:04 
 收件人:&amp;nbsp;"ErLinErYi/PlantsVsZombies"<PlantsVsZombies@noreply.github.com&amp;gt;; 
 抄送:&amp;nbsp;"danieldaniel"<danielstock@qq.com&amp;gt;;"Author"<author@noreply.github.com&amp;gt;; 
 主题:&amp;nbsp;Re: [ErLinErYi/PlantsVsZombies] 完整代码下载 (#3) 
 
 
 
 由于我正在重建仓库，请稍等一些时间就可以下载了。  
   
   
   
  ---原始邮件---  
  发件人: "danielstock"<notifications@github.com&amp;amp;gt;  
  发送时间: 2020年2月29日(周六) 中午11:33  
  收件人: "ErLinErYi/PlantsVsZombies"<PlantsVsZombies@noreply.github.com&amp;amp;gt;;  
  抄送: "Subscribed"<subscribed@noreply.github.com&amp;amp;gt;;  
  主题: [ErLinErYi/PlantsVsZombies] 完整代码下载 (#3)  
   
   
   
  您好，想学习手机游戏开发，能否提供完整代码包下载，谢谢啦
