### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by KeyFac** [ErLinErYi/PlantsVsZombies#4]
建议做一下Wiki和发布Release（GitHub里的），这样的话它会自动打包为.zip和.tar.gz

**Comment by ErLinErYi** [comment]
我已在码云创建了release版https://gitee.com/GITLZ/PlantsVsZombies



---原始邮件---
发件人: "GLgele"<notifications@github.com&gt;
发送时间: 2020年3月9日(周一) 中午12:45
收件人: "ErLinErYi/PlantsVsZombies"<PlantsVsZombies@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [ErLinErYi/PlantsVsZombies] 建议 (#4)



建议做一下Wiki和发布Release（GitHub里的），这样的话它会自动打包为.zip和.tar.gz
